package serviceenseignement.vues;

import donnes.date.DateConvention;
import donnes.preconvention.PreConvention;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.BorderFactory;
import javax.swing.border.TitledBorder;

/**
 * Fenêtre des détails de la préconvention à valider 
 * sélectionnée dans le service enseignement 
 * @author marieroca
 */
public class DetailsPreConv extends javax.swing.JFrame {
    private ListePreConv fenMere;
    private Long pc;
    private boolean stageCursus, duree, tuteur;
    private boolean verifStageCursus, verifDuree;

    /**
     * Creates new form DetailsPreConv
     * @param fenMere fenêtre de la liste des préconventions du service enseignement
     * @param pc préconvention à valider
     */
    public DetailsPreConv(ListePreConv fenMere, Long pc) {
        initComponents();
        this.fenMere = fenMere;
        this.pc = pc;
        this.lNomPrenomEntreprise.setText("de " + this.fenMere.getConv().get(pc).getEtudiant().getPrenom() + " " + this.fenMere.getConv().get(pc).getEtudiant().getNom() + " à " + this.fenMere.getConv().get(pc).getEntreprise());
        this.lNom.setText("Nom : " + this.fenMere.getConv().get(pc).getEtudiant().getNom());
        this.lPrenom.setText("Prénom : " + this.fenMere.getConv().get(pc).getEtudiant().getPrenom());
        this.lDiplome.setText(this.fenMere.getConv().get(pc).getEtudiant().getDiplome().getNiveau() + " " + this.fenMere.getConv().get(pc).getEtudiant().getDiplome().getIntitule());
        DateConvention dDeb = this.fenMere.getConv().get(pc).getDateDeb();
        DateConvention dFin = this.fenMere.getConv().get(pc).getDateFin();
        this.tfDateDeb.setText(dDeb.toString());
        this.tfDateFin.setText(dFin.toString());
        //On affiche la durée sous le format "? mois et ? jours"
        String duree = DateConvention.nbMois(dDeb.getDate(), dFin.getDate()) + " mois " + DateConvention.nbJours(dDeb.getDate(), dFin.getDate()) + " jours";
        this.tfDuree.setText(duree);
        this.stageCursus = false; 
        this.duree = false; 
        this.tuteur = false;
        this.verifStageCursus = false;
        this.verifDuree = false;
        //Le panel "Enseignant Chercheur" a un titre rouge tant qu'on a pas affecté de tuteur
        TitledBorder border = BorderFactory.createTitledBorder("Enseignant Chercheur");
        border.setTitleColor(Color.RED);
        this.pTuteur.setBorder(border);
        
        this.tfAssurNom.setText(this.fenMere.getConv().get(pc).getEtudiant().getAssurance());
        this.tfAssurNumContrat.setText(this.fenMere.getConv().get(pc).getEtudiant().getContrat());
        this.tfEntNom.setText(this.fenMere.getConv().get(pc).getEntreprise());
        this.tfGratification.setText(this.fenMere.getConv().get(pc).getGratification()+"");
        this.tfResumeActivites.setText(this.fenMere.getConv().get(pc).getResumeSujet());
        this.tfSIREN.setText(this.fenMere.getConv().get(pc).getNumEntreprise());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puVerif = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        bPuOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNomPrenomEntreprise = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfEntNom = new javax.swing.JTextField();
        tfSIREN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfGratification = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pDuree = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfDateDeb = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDuree = new javax.swing.JTextField();
        tfDateFin = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDureeMin = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jVerifierDuree = new javax.swing.JButton();
        pStageCursus = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lDiplome = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfResumeActivites = new javax.swing.JTextField();
        bOkStageCursus = new javax.swing.JButton();
        bNonOkStageCursus = new javax.swing.JButton();
        pTuteur = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tfTuteur = new javax.swing.JTextField();
        pDetailsLegaux = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lNom = new javax.swing.JLabel();
        lPrenom = new javax.swing.JLabel();
        tfAssurNom = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfAssurNumContrat = new javax.swing.JTextField();
        bValider = new javax.swing.JButton();
        bAnnule = new javax.swing.JButton();

        puVerif.setMinimumSize(new java.awt.Dimension(363, 100));

        jLabel2.setText("Merci de tout vérifier et de rentrer un tuteur");

        bPuOk.setText("Ok");
        bPuOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPuOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puVerifLayout = new javax.swing.GroupLayout(puVerif.getContentPane());
        puVerif.getContentPane().setLayout(puVerifLayout);
        puVerifLayout.setHorizontalGroup(
            puVerifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puVerifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puVerifLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPuOk)
                .addGap(102, 102, 102))
        );
        puVerifLayout.setVerticalGroup(
            puVerifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puVerifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPuOk))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Service Enseignement - Détails");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Détails à valider de la pré-convention");

        lNomPrenomEntreprise.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lNomPrenomEntreprise.setText("de NOM Prénom à Entreprise");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Entreprise/Institution d'accueil"));

        jLabel9.setText("Nom :");

        jLabel16.setText("SIREN :");

        tfEntNom.setEditable(false);
        tfEntNom.setText("nomEnt");

        tfSIREN.setEditable(false);
        tfSIREN.setText("numSIREN");

        jLabel7.setText("Gratification :");

        tfGratification.setEditable(false);
        tfGratification.setText("jTextField1");

        jLabel8.setText("€");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSIREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEntNom)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfGratification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfGratification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tfEntNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfSIREN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pDuree.setBorder(javax.swing.BorderFactory.createTitledBorder("Durée du stage"));

        jLabel3.setText("Date de début :");

        tfDateDeb.setEditable(false);
        tfDateDeb.setText("dateDeb");

        jLabel5.setText("Durée :");

        tfDuree.setEditable(false);
        tfDuree.setText("duree");

        tfDateFin.setEditable(false);
        tfDateFin.setText("dateFin");

        jLabel4.setText("Date de fin :");

        jLabel6.setText("Durée min necessaire pour valider l'UE :");

        tfDureeMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel15.setText("mois");

        jVerifierDuree.setText("Vérifier");
        jVerifierDuree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerifierDureeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pDureeLayout = new javax.swing.GroupLayout(pDuree);
        pDuree.setLayout(pDureeLayout);
        pDureeLayout.setHorizontalGroup(
            pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDureeLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDureeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pDureeLayout.createSequentialGroup()
                .addGroup(pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDureeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDureeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jVerifierDuree)))
                .addContainerGap())
        );
        pDureeLayout.setVerticalGroup(
            pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDureeLayout.createSequentialGroup()
                .addGroup(pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDateDeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDureeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jVerifierDuree)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDureeLayout.createSequentialGroup()
                        .addGroup(pDureeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pStageCursus.setBorder(javax.swing.BorderFactory.createTitledBorder("Stage et cursus"));

        jLabel13.setText("Vérifier que le stage est bien inscrit dans ce cursus et que ");

        jLabel14.setText("les activités relèvent bien des compétences et du niveau.");

        lDiplome.setText("diplome");

        jLabel27.setText("Diplôme");

        jLabel29.setText("Résumé du sujet et des activités");

        tfResumeActivites.setEditable(false);
        tfResumeActivites.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfResumeActivites.setText("resume");

        bOkStageCursus.setText("Ok");
        bOkStageCursus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkStageCursusActionPerformed(evt);
            }
        });

        bNonOkStageCursus.setText("Non");
        bNonOkStageCursus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNonOkStageCursusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pStageCursusLayout = new javax.swing.GroupLayout(pStageCursus);
        pStageCursus.setLayout(pStageCursusLayout);
        pStageCursusLayout.setHorizontalGroup(
            pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStageCursusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pStageCursusLayout.createSequentialGroup()
                        .addGroup(pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pStageCursusLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDiplome))
                            .addComponent(jLabel29))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pStageCursusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bNonOkStageCursus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bOkStageCursus)))
                .addContainerGap())
            .addGroup(pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pStageCursusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tfResumeActivites)
                    .addContainerGap()))
        );
        pStageCursusLayout.setVerticalGroup(
            pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStageCursusLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDiplome)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOkStageCursus)
                    .addComponent(bNonOkStageCursus)))
            .addGroup(pStageCursusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pStageCursusLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(tfResumeActivites, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        pTuteur.setBorder(javax.swing.BorderFactory.createTitledBorder("Enseignant Chercheur"));

        jLabel21.setText("Tuteur enseignant pour le stage :");

        tfTuteur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTuteurKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pTuteurLayout = new javax.swing.GroupLayout(pTuteur);
        pTuteur.setLayout(pTuteurLayout);
        pTuteurLayout.setHorizontalGroup(
            pTuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTuteurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTuteurLayout.setVerticalGroup(
            pTuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel21)
                .addComponent(tfTuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pDetailsLegaux.setBorder(javax.swing.BorderFactory.createTitledBorder("Données étudiant"));

        jLabel22.setText("Étudiant");

        lNom.setText("Nom :");

        lPrenom.setText("Prénom :");

        tfAssurNom.setEditable(false);
        tfAssurNom.setText("nomAssur");

        jLabel19.setText("Nom :");

        jLabel20.setText("Numéro de contrat :");

        tfAssurNumContrat.setEditable(false);
        tfAssurNumContrat.setText("numContrat");

        javax.swing.GroupLayout pDetailsLegauxLayout = new javax.swing.GroupLayout(pDetailsLegaux);
        pDetailsLegaux.setLayout(pDetailsLegauxLayout);
        pDetailsLegauxLayout.setHorizontalGroup(
            pDetailsLegauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailsLegauxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDetailsLegauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDetailsLegauxLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(7, 7, 7)
                        .addGroup(pDetailsLegauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPrenom)
                            .addComponent(lNom)))
                    .addGroup(pDetailsLegauxLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAssurNom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAssurNumContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pDetailsLegauxLayout.setVerticalGroup(
            pDetailsLegauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDetailsLegauxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pDetailsLegauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPrenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDetailsLegauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfAssurNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tfAssurNumContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pStageCursus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDuree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lNomPrenomEntreprise))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pTuteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDetailsLegaux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNomPrenomEntreprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pStageCursus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDetailsLegaux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bValider.setText("Valider");
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        bAnnule.setText("Annuler");
        bAnnule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bAnnule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bValider)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bValider)
                    .addComponent(bAnnule))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Évènement généré lors du clic sur "Annuler"
     * Fermeture de la fenêtre
     * @param evt 
     */
    private void bAnnuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnuleActionPerformed
        this.fenMere.maj();
        this.dispose();
    }//GEN-LAST:event_bAnnuleActionPerformed

    /**
     * Évènement généré lors du clic sur "Valider"
     * On ouvre une popup "renseignez tous les champs" si il manque une vérification
     * @param evt 
     */
    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        PreConvention p = this.fenMere.getConv().get(pc);
        //Si le tuteur n'a pas été affecté
        if(this.tfTuteur.getText().equals(""))
            //On ouvre la popup "Merci de tout vérifier et de rentrer un tuteur"
            this.puVerif.setVisible(true);
        //Sinon
        else{
            //Si tout a été vérifié (durée et sujet)
            if(this.verifStageCursus == true && this.verifDuree == true){
                //Si la durée et le stage ont été validés 
                if(this.duree && this.stageCursus){
                    //On valide la préconv
                    p.setValidite(true);
                //Sinon
                }else{
                    //On refuse la préconv 
                    p.setValidite(false);
                }
                //on bouge la préconvention des conv à traiter aux conv traitées
                this.fenMere.getS().getConv().remove(pc);
                this.fenMere.getS().getConvTraitees().putIfAbsent(pc, p);
                try {
                    //On l'envoie au service des stages
                    this.fenMere.getS().envoyer(p);
                } catch (NamingException ex) {
                    Logger.getLogger(DetailsPreConv.class.getName()).log(Level.SEVERE, null, ex);
                }
                //On ferme la fenêtre
                this.fenMere.maj();
                this.dispose();
            }else{
                this.puVerif.setVisible(true);
            }
        }    
    }//GEN-LAST:event_bValiderActionPerformed

    /**
     * Évènement généré lors du clic sur "Non" dans le panel Stage et cursus
     * @param evt 
     */
    private void bNonOkStageCursusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNonOkStageCursusActionPerformed
        //Stage et cursus refusés
        this.stageCursus = false;
        
        //On affiche visuellement que stage/cursus ont été vérifiés et refusés
        //Titre du panel en rouge 
        TitledBorder border = BorderFactory.createTitledBorder("Stage et cursus");
        border.setTitleColor(Color.RED);
        this.pStageCursus.setBorder(border);
        
        //Stage et cursus vérifiés
        this.verifStageCursus = true;
    }//GEN-LAST:event_bNonOkStageCursusActionPerformed

    /**
     * Évènement généré lors du clic sur "Vérifier" dans le panel Durée du stage
     * @param evt 
     */
    private void jVerifierDureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerifierDureeActionPerformed
        PreConvention p = this.fenMere.getConv().get(pc);
        int nbMois = DateConvention.nbMois(p.getDateDeb().getDate(), p.getDateFin().getDate());
        
        //Je récupère le nombre minimum de mois pour valider l'UE
        int nbMoisMin = ((Number)this.tfDureeMin.getValue()).intValue();
        
        //Je le compare avec la durée du stage
        boolean bonneDuree = this.fenMere.getS().duree(p, nbMoisMin);
        
        //Si la durée est  suffisante pour valider l'UE
        if(bonneDuree){
            //la durée est bonne
            this.duree = true;
            //J'écris la durée en noir
            this.tfDureeMin.setForeground(Color.BLACK);
            //On affiche visuellement que la durée a été vérifiée et qu'elle est valide
            //Titre du panel en vert
            TitledBorder border = BorderFactory.createTitledBorder("Durée du stage");
            border.setTitleColor(Color.GREEN);
            this.pDuree.setBorder(border);
        //Sinon
        }else{
            //la durée n'est pas bonne
            this.duree = false;
            //J'écris la durée en rouge
            this.tfDureeMin.setForeground(Color.red);
            //On affiche visuellement que la durée a été vérifiée et qu'elle est refusée
            //Titre du panel en rouge
            TitledBorder border = BorderFactory.createTitledBorder("Durée du stage");
            border.setTitleColor(Color.RED);
            this.pDuree.setBorder(border);
        }
        //on a vérifié la durée
        this.verifDuree = true;
    }//GEN-LAST:event_jVerifierDureeActionPerformed

    /**
     * Évènement généré lors du clic sur "Ok" dans le panel Stage et cursus
     * @param evt 
     */
    private void bOkStageCursusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkStageCursusActionPerformed
        //Stage cursur validées
        this.stageCursus = true;
        //Stage et cursus vérifiés
        this.verifStageCursus = true;
        //On affiche visuellement que le stage et le cursus ont été vérifiés 
        //et qu'ils sont validés
        //Titre du panel en vert
        TitledBorder border = BorderFactory.createTitledBorder("Stage et cursus");
        border.setTitleColor(Color.GREEN);
        this.pStageCursus.setBorder(border);
    }//GEN-LAST:event_bOkStageCursusActionPerformed

    /**
     * Évènement généré lors du clic sur "Ok" de la pop up "renseignez tous les champs"
     * On ferme la fenêtre
     * @param evt 
     */
    private void bPuOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPuOkActionPerformed
        this.puVerif.dispose();
    }//GEN-LAST:event_bPuOkActionPerformed

    /**
     * Évènement généré lorsque l'utilisateur entre un nom de tuteur
     * On affiche visuellement qu'un tuteur est renseigné dès que la textfield n'est plus vide
     * @param evt 
     */
    private void tfTuteurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTuteurKeyTyped
        //Si la textfield est vide
        //On affiche visuellement qu'aucun tuteur n'est rentré en mettant le titre 
        //du panel "Enseignant Chercheur" en rouge
        if(this.tfTuteur.getText().equals("")){
            TitledBorder border = BorderFactory.createTitledBorder("Enseignant Chercheur");
            border.setTitleColor(Color.RED);
            this.pTuteur.setBorder(border);
        //Sinon
        //On affiche visuellement qu'un tuteur est rentré en mettant le titre 
        //du panel "Enseignant Chercheur" en vert
        //Aucune vérification n'est faite sur le nom du tuteur, on considère l'utilisateur intelligent
        }else{
            TitledBorder border = BorderFactory.createTitledBorder("Enseignant Chercheur");
            border.setTitleColor(Color.GREEN);
            this.pTuteur.setBorder(border);
        }
    }//GEN-LAST:event_tfTuteurKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsPreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsPreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsPreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsPreConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DetailsPreConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnule;
    private javax.swing.JButton bNonOkStageCursus;
    private javax.swing.JButton bOkStageCursus;
    private javax.swing.JButton bPuOk;
    private javax.swing.JButton bValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jVerifierDuree;
    private javax.swing.JLabel lDiplome;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lNomPrenomEntreprise;
    private javax.swing.JLabel lPrenom;
    private javax.swing.JPanel pDetailsLegaux;
    private javax.swing.JPanel pDuree;
    private javax.swing.JPanel pStageCursus;
    private javax.swing.JPanel pTuteur;
    private javax.swing.JDialog puVerif;
    private javax.swing.JTextField tfAssurNom;
    private javax.swing.JTextField tfAssurNumContrat;
    private javax.swing.JFormattedTextField tfDateDeb;
    private javax.swing.JFormattedTextField tfDateFin;
    private javax.swing.JTextField tfDuree;
    private javax.swing.JFormattedTextField tfDureeMin;
    private javax.swing.JTextField tfEntNom;
    private javax.swing.JTextField tfGratification;
    private javax.swing.JTextField tfResumeActivites;
    private javax.swing.JTextField tfSIREN;
    private javax.swing.JTextField tfTuteur;
    // End of variables declaration//GEN-END:variables
}
